// Generated by gencpp from file my_msgs/Chassis.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_CHASSIS_H
#define MY_MSGS_MESSAGE_CHASSIS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_msgs/Header.h>
#include <my_msgs/Common_VehicleSignal.h>
#include <my_msgs/Chassis_ChassisGPS.h>
#include <my_msgs/Common_EngageAdvise.h>

namespace my_msgs
{
template <class ContainerAllocator>
struct Chassis_
{
  typedef Chassis_<ContainerAllocator> Type;

  Chassis_()
    : engine_started(false)
    , engine_rpm(0.0)
    , speed_mps(0.0)
    , odometer_m(0.0)
    , fuel_range_m(0)
    , throttle_percentage(0.0)
    , brake_percentage(0.0)
    , steering_percentage(0.0)
    , steering_torque_nm(0.0)
    , parking_brake(false)
    , high_beam_signal(false)
    , low_beam_signal(false)
    , left_turn_signal(false)
    , right_turn_signal(false)
    , horn(false)
    , wiper(false)
    , disengage_status(false)
    , driving_mode(0)
    , error_code(0)
    , gear_location(0)
    , steering_timestamp(0.0)
    , header()
    , chassis_error_mask(0)
    , signal()
    , chassis_gps()
    , engage_advice()  {
    }
  Chassis_(const ContainerAllocator& _alloc)
    : engine_started(false)
    , engine_rpm(0.0)
    , speed_mps(0.0)
    , odometer_m(0.0)
    , fuel_range_m(0)
    , throttle_percentage(0.0)
    , brake_percentage(0.0)
    , steering_percentage(0.0)
    , steering_torque_nm(0.0)
    , parking_brake(false)
    , high_beam_signal(false)
    , low_beam_signal(false)
    , left_turn_signal(false)
    , right_turn_signal(false)
    , horn(false)
    , wiper(false)
    , disengage_status(false)
    , driving_mode(0)
    , error_code(0)
    , gear_location(0)
    , steering_timestamp(0.0)
    , header(_alloc)
    , chassis_error_mask(0)
    , signal(_alloc)
    , chassis_gps(_alloc)
    , engage_advice(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _engine_started_type;
  _engine_started_type engine_started;

   typedef double _engine_rpm_type;
  _engine_rpm_type engine_rpm;

   typedef double _speed_mps_type;
  _speed_mps_type speed_mps;

   typedef double _odometer_m_type;
  _odometer_m_type odometer_m;

   typedef int32_t _fuel_range_m_type;
  _fuel_range_m_type fuel_range_m;

   typedef double _throttle_percentage_type;
  _throttle_percentage_type throttle_percentage;

   typedef double _brake_percentage_type;
  _brake_percentage_type brake_percentage;

   typedef double _steering_percentage_type;
  _steering_percentage_type steering_percentage;

   typedef double _steering_torque_nm_type;
  _steering_torque_nm_type steering_torque_nm;

   typedef uint8_t _parking_brake_type;
  _parking_brake_type parking_brake;

   typedef uint8_t _high_beam_signal_type;
  _high_beam_signal_type high_beam_signal;

   typedef uint8_t _low_beam_signal_type;
  _low_beam_signal_type low_beam_signal;

   typedef uint8_t _left_turn_signal_type;
  _left_turn_signal_type left_turn_signal;

   typedef uint8_t _right_turn_signal_type;
  _right_turn_signal_type right_turn_signal;

   typedef uint8_t _horn_type;
  _horn_type horn;

   typedef uint8_t _wiper_type;
  _wiper_type wiper;

   typedef uint8_t _disengage_status_type;
  _disengage_status_type disengage_status;

   typedef uint8_t _driving_mode_type;
  _driving_mode_type driving_mode;

   typedef uint8_t _error_code_type;
  _error_code_type error_code;

   typedef uint8_t _gear_location_type;
  _gear_location_type gear_location;

   typedef double _steering_timestamp_type;
  _steering_timestamp_type steering_timestamp;

   typedef  ::my_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _chassis_error_mask_type;
  _chassis_error_mask_type chassis_error_mask;

   typedef  ::my_msgs::Common_VehicleSignal_<ContainerAllocator>  _signal_type;
  _signal_type signal;

   typedef  ::my_msgs::Chassis_ChassisGPS_<ContainerAllocator>  _chassis_gps_type;
  _chassis_gps_type chassis_gps;

   typedef  ::my_msgs::Common_EngageAdvise_<ContainerAllocator>  _engage_advice_type;
  _engage_advice_type engage_advice;




  typedef boost::shared_ptr< ::my_msgs::Chassis_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::Chassis_<ContainerAllocator> const> ConstPtr;

}; // struct Chassis_

typedef ::my_msgs::Chassis_<std::allocator<void> > Chassis;

typedef boost::shared_ptr< ::my_msgs::Chassis > ChassisPtr;
typedef boost::shared_ptr< ::my_msgs::Chassis const> ChassisConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::Chassis_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::Chassis_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::Chassis_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::Chassis_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::Chassis_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::Chassis_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::Chassis_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::Chassis_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::Chassis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2893873e3c008408a7232785a73f2427";
  }

  static const char* value(const ::my_msgs::Chassis_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2893873e3c008408ULL;
  static const uint64_t static_value2 = 0xa7232785a73f2427ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::Chassis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/Chassis";
  }

  static const char* value(const ::my_msgs::Chassis_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::Chassis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool engine_started\n\
float64 engine_rpm\n\
float64 speed_mps\n\
float64 odometer_m\n\
int32 fuel_range_m\n\
float64 throttle_percentage\n\
float64 brake_percentage\n\
float64 steering_percentage\n\
float64 steering_torque_nm\n\
bool parking_brake\n\
bool high_beam_signal\n\
bool low_beam_signal\n\
bool left_turn_signal\n\
bool right_turn_signal\n\
bool horn\n\
bool wiper\n\
bool disengage_status\n\
uint8 driving_mode \n\
uint8 error_code  \n\
uint8 gear_location  \n\
float64 steering_timestamp\n\
my_msgs/Header header\n\
int32 chassis_error_mask\n\
my_msgs/Common_VehicleSignal signal  \n\
my_msgs/Chassis_ChassisGPS chassis_gps  \n\
my_msgs/Common_EngageAdvise engage_advice  \n\
================================================================================\n\
MSG: my_msgs/Header\n\
float64 timestamp_sec\n\
string module_name\n\
uint32 sequence_num\n\
uint32 lidar_timestamp\n\
uint32 camera_timestamp\n\
uint32 radar_timestamp\n\
uint32 version\n\
my_msgs/Status status\n\
\n\
================================================================================\n\
MSG: my_msgs/Status\n\
int32 error_code\n\
\n\
================================================================================\n\
MSG: my_msgs/Common_VehicleSignal\n\
my_msgs/TurnSignal turn_signal\n\
bool high_beam\n\
bool low_beam\n\
bool horn\n\
bool emergency_light\n\
================================================================================\n\
MSG: my_msgs/TurnSignal\n\
int32 TURN_NONE\n\
int32 TURN_LEFT\n\
int32 TURN_RIGHT\n\
================================================================================\n\
MSG: my_msgs/Chassis_ChassisGPS\n\
float64 latitude\n\
float64 longitude\n\
bool gps_valid\n\
int32 year\n\
int32 month\n\
int32 day\n\
int32 hours\n\
int32 minutes\n\
int32 seconds\n\
float64 compass_direction\n\
float64 pdop\n\
bool is_gps_fault\n\
bool is_inferred\n\
float64 altitude\n\
float64 heading\n\
float64 hdop\n\
float64 vdop\n\
uint8 quality\n\
int32 num_satellites\n\
float64 gps_speed\n\
================================================================================\n\
MSG: my_msgs/Common_EngageAdvise\n\
uint8 advice\n\
string reason\n\
";
  }

  static const char* value(const ::my_msgs::Chassis_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::Chassis_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.engine_started);
      stream.next(m.engine_rpm);
      stream.next(m.speed_mps);
      stream.next(m.odometer_m);
      stream.next(m.fuel_range_m);
      stream.next(m.throttle_percentage);
      stream.next(m.brake_percentage);
      stream.next(m.steering_percentage);
      stream.next(m.steering_torque_nm);
      stream.next(m.parking_brake);
      stream.next(m.high_beam_signal);
      stream.next(m.low_beam_signal);
      stream.next(m.left_turn_signal);
      stream.next(m.right_turn_signal);
      stream.next(m.horn);
      stream.next(m.wiper);
      stream.next(m.disengage_status);
      stream.next(m.driving_mode);
      stream.next(m.error_code);
      stream.next(m.gear_location);
      stream.next(m.steering_timestamp);
      stream.next(m.header);
      stream.next(m.chassis_error_mask);
      stream.next(m.signal);
      stream.next(m.chassis_gps);
      stream.next(m.engage_advice);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Chassis_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::Chassis_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::Chassis_<ContainerAllocator>& v)
  {
    s << indent << "engine_started: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.engine_started);
    s << indent << "engine_rpm: ";
    Printer<double>::stream(s, indent + "  ", v.engine_rpm);
    s << indent << "speed_mps: ";
    Printer<double>::stream(s, indent + "  ", v.speed_mps);
    s << indent << "odometer_m: ";
    Printer<double>::stream(s, indent + "  ", v.odometer_m);
    s << indent << "fuel_range_m: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fuel_range_m);
    s << indent << "throttle_percentage: ";
    Printer<double>::stream(s, indent + "  ", v.throttle_percentage);
    s << indent << "brake_percentage: ";
    Printer<double>::stream(s, indent + "  ", v.brake_percentage);
    s << indent << "steering_percentage: ";
    Printer<double>::stream(s, indent + "  ", v.steering_percentage);
    s << indent << "steering_torque_nm: ";
    Printer<double>::stream(s, indent + "  ", v.steering_torque_nm);
    s << indent << "parking_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.parking_brake);
    s << indent << "high_beam_signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.high_beam_signal);
    s << indent << "low_beam_signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.low_beam_signal);
    s << indent << "left_turn_signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_turn_signal);
    s << indent << "right_turn_signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_turn_signal);
    s << indent << "horn: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.horn);
    s << indent << "wiper: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wiper);
    s << indent << "disengage_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.disengage_status);
    s << indent << "driving_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.driving_mode);
    s << indent << "error_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "gear_location: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_location);
    s << indent << "steering_timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.steering_timestamp);
    s << indent << "header: ";
    s << std::endl;
    Printer< ::my_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "chassis_error_mask: ";
    Printer<int32_t>::stream(s, indent + "  ", v.chassis_error_mask);
    s << indent << "signal: ";
    s << std::endl;
    Printer< ::my_msgs::Common_VehicleSignal_<ContainerAllocator> >::stream(s, indent + "  ", v.signal);
    s << indent << "chassis_gps: ";
    s << std::endl;
    Printer< ::my_msgs::Chassis_ChassisGPS_<ContainerAllocator> >::stream(s, indent + "  ", v.chassis_gps);
    s << indent << "engage_advice: ";
    s << std::endl;
    Printer< ::my_msgs::Common_EngageAdvise_<ContainerAllocator> >::stream(s, indent + "  ", v.engage_advice);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_CHASSIS_H
