// Generated by gencpp from file my_msgs/GnssBestPose.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_GNSSBESTPOSE_H
#define MY_MSGS_MESSAGE_GNSSBESTPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_msgs/Header.h>

namespace my_msgs
{
template <class ContainerAllocator>
struct GnssBestPose_
{
  typedef GnssBestPose_<ContainerAllocator> Type;

  GnssBestPose_()
    : header()
    , measurement_time(0.0)
    , sol_status(0)
    , sol_type(0)
    , latitude(0.0)
    , longitude(0.0)
    , height_msl(0.0)
    , undulation(0.0)
    , datum_id(0)
    , latitude_std_dev(0.0)
    , longitude_std_dev(0.0)
    , height_std_dev(0.0)
    , base_station_id()
    , differential_age(0.0)
    , solution_age(0.0)
    , num_sats_tracked(0)
    , num_sats_in_solution(0)
    , num_sats_l1(0)
    , num_sats_multi(0)
    , reserved(0)
    , extended_solution_status(0)
    , galileo_beidou_used_mask(0)
    , gps_glonass_used_mask(0)  {
    }
  GnssBestPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , measurement_time(0.0)
    , sol_status(0)
    , sol_type(0)
    , latitude(0.0)
    , longitude(0.0)
    , height_msl(0.0)
    , undulation(0.0)
    , datum_id(0)
    , latitude_std_dev(0.0)
    , longitude_std_dev(0.0)
    , height_std_dev(0.0)
    , base_station_id(_alloc)
    , differential_age(0.0)
    , solution_age(0.0)
    , num_sats_tracked(0)
    , num_sats_in_solution(0)
    , num_sats_l1(0)
    , num_sats_multi(0)
    , reserved(0)
    , extended_solution_status(0)
    , galileo_beidou_used_mask(0)
    , gps_glonass_used_mask(0)  {
  (void)_alloc;
    }



   typedef  ::my_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _measurement_time_type;
  _measurement_time_type measurement_time;

   typedef int32_t _sol_status_type;
  _sol_status_type sol_status;

   typedef int32_t _sol_type_type;
  _sol_type_type sol_type;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _height_msl_type;
  _height_msl_type height_msl;

   typedef double _undulation_type;
  _undulation_type undulation;

   typedef int32_t _datum_id_type;
  _datum_id_type datum_id;

   typedef double _latitude_std_dev_type;
  _latitude_std_dev_type latitude_std_dev;

   typedef double _longitude_std_dev_type;
  _longitude_std_dev_type longitude_std_dev;

   typedef double _height_std_dev_type;
  _height_std_dev_type height_std_dev;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _base_station_id_type;
  _base_station_id_type base_station_id;

   typedef double _differential_age_type;
  _differential_age_type differential_age;

   typedef double _solution_age_type;
  _solution_age_type solution_age;

   typedef int32_t _num_sats_tracked_type;
  _num_sats_tracked_type num_sats_tracked;

   typedef int32_t _num_sats_in_solution_type;
  _num_sats_in_solution_type num_sats_in_solution;

   typedef int32_t _num_sats_l1_type;
  _num_sats_l1_type num_sats_l1;

   typedef int32_t _num_sats_multi_type;
  _num_sats_multi_type num_sats_multi;

   typedef int32_t _reserved_type;
  _reserved_type reserved;

   typedef int32_t _extended_solution_status_type;
  _extended_solution_status_type extended_solution_status;

   typedef int32_t _galileo_beidou_used_mask_type;
  _galileo_beidou_used_mask_type galileo_beidou_used_mask;

   typedef int32_t _gps_glonass_used_mask_type;
  _gps_glonass_used_mask_type gps_glonass_used_mask;




  typedef boost::shared_ptr< ::my_msgs::GnssBestPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::GnssBestPose_<ContainerAllocator> const> ConstPtr;

}; // struct GnssBestPose_

typedef ::my_msgs::GnssBestPose_<std::allocator<void> > GnssBestPose;

typedef boost::shared_ptr< ::my_msgs::GnssBestPose > GnssBestPosePtr;
typedef boost::shared_ptr< ::my_msgs::GnssBestPose const> GnssBestPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::GnssBestPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::GnssBestPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::GnssBestPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::GnssBestPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::GnssBestPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::GnssBestPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::GnssBestPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::GnssBestPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::GnssBestPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d02b4f3ffdb7dda965124b9a452cacfc";
  }

  static const char* value(const ::my_msgs::GnssBestPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd02b4f3ffdb7dda9ULL;
  static const uint64_t static_value2 = 0x65124b9a452cacfcULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::GnssBestPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/GnssBestPose";
  }

  static const char* value(const ::my_msgs::GnssBestPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::GnssBestPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/Header header\n\
float64 measurement_time\n\
int32 sol_status\n\
int32 sol_type\n\
float64 latitude \n\
float64 longitude\n\
float64 height_msl\n\
float64 undulation \n\
int32 datum_id\n\
float64 latitude_std_dev\n\
float64 longitude_std_dev\n\
float64 height_std_dev \n\
string base_station_id \n\
float64 differential_age \n\
float64 solution_age  \n\
int32 num_sats_tracked \n\
int32 num_sats_in_solution \n\
int32 num_sats_l1\n\
int32 num_sats_multi  \n\
int32 reserved \n\
int32 extended_solution_status \n\
int32 galileo_beidou_used_mask\n\
int32 gps_glonass_used_mask\n\
================================================================================\n\
MSG: my_msgs/Header\n\
float64 timestamp_sec\n\
string module_name\n\
uint32 sequence_num\n\
uint32 lidar_timestamp\n\
uint32 camera_timestamp\n\
uint32 radar_timestamp\n\
uint32 version\n\
my_msgs/Status status\n\
\n\
================================================================================\n\
MSG: my_msgs/Status\n\
int32 error_code\n\
";
  }

  static const char* value(const ::my_msgs::GnssBestPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::GnssBestPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.measurement_time);
      stream.next(m.sol_status);
      stream.next(m.sol_type);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.height_msl);
      stream.next(m.undulation);
      stream.next(m.datum_id);
      stream.next(m.latitude_std_dev);
      stream.next(m.longitude_std_dev);
      stream.next(m.height_std_dev);
      stream.next(m.base_station_id);
      stream.next(m.differential_age);
      stream.next(m.solution_age);
      stream.next(m.num_sats_tracked);
      stream.next(m.num_sats_in_solution);
      stream.next(m.num_sats_l1);
      stream.next(m.num_sats_multi);
      stream.next(m.reserved);
      stream.next(m.extended_solution_status);
      stream.next(m.galileo_beidou_used_mask);
      stream.next(m.gps_glonass_used_mask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GnssBestPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::GnssBestPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::GnssBestPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::my_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "measurement_time: ";
    Printer<double>::stream(s, indent + "  ", v.measurement_time);
    s << indent << "sol_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sol_status);
    s << indent << "sol_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sol_type);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "height_msl: ";
    Printer<double>::stream(s, indent + "  ", v.height_msl);
    s << indent << "undulation: ";
    Printer<double>::stream(s, indent + "  ", v.undulation);
    s << indent << "datum_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.datum_id);
    s << indent << "latitude_std_dev: ";
    Printer<double>::stream(s, indent + "  ", v.latitude_std_dev);
    s << indent << "longitude_std_dev: ";
    Printer<double>::stream(s, indent + "  ", v.longitude_std_dev);
    s << indent << "height_std_dev: ";
    Printer<double>::stream(s, indent + "  ", v.height_std_dev);
    s << indent << "base_station_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.base_station_id);
    s << indent << "differential_age: ";
    Printer<double>::stream(s, indent + "  ", v.differential_age);
    s << indent << "solution_age: ";
    Printer<double>::stream(s, indent + "  ", v.solution_age);
    s << indent << "num_sats_tracked: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_sats_tracked);
    s << indent << "num_sats_in_solution: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_sats_in_solution);
    s << indent << "num_sats_l1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_sats_l1);
    s << indent << "num_sats_multi: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_sats_multi);
    s << indent << "reserved: ";
    Printer<int32_t>::stream(s, indent + "  ", v.reserved);
    s << indent << "extended_solution_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.extended_solution_status);
    s << indent << "galileo_beidou_used_mask: ";
    Printer<int32_t>::stream(s, indent + "  ", v.galileo_beidou_used_mask);
    s << indent << "gps_glonass_used_mask: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gps_glonass_used_mask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_GNSSBESTPOSE_H
