// Generated by gencpp from file my_msgs/GpsQuality.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_GPSQUALITY_H
#define MY_MSGS_MESSAGE_GPSQUALITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_msgs
{
template <class ContainerAllocator>
struct GpsQuality_
{
  typedef GpsQuality_<ContainerAllocator> Type;

  GpsQuality_()
    : FIX_NO(0)
    , FIX_2D(0)
    , FIX_3D(0)
    , FIX_INVALID(0)  {
    }
  GpsQuality_(const ContainerAllocator& _alloc)
    : FIX_NO(0)
    , FIX_2D(0)
    , FIX_3D(0)
    , FIX_INVALID(0)  {
  (void)_alloc;
    }



   typedef int32_t _FIX_NO_type;
  _FIX_NO_type FIX_NO;

   typedef int32_t _FIX_2D_type;
  _FIX_2D_type FIX_2D;

   typedef int32_t _FIX_3D_type;
  _FIX_3D_type FIX_3D;

   typedef int32_t _FIX_INVALID_type;
  _FIX_INVALID_type FIX_INVALID;




  typedef boost::shared_ptr< ::my_msgs::GpsQuality_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::GpsQuality_<ContainerAllocator> const> ConstPtr;

}; // struct GpsQuality_

typedef ::my_msgs::GpsQuality_<std::allocator<void> > GpsQuality;

typedef boost::shared_ptr< ::my_msgs::GpsQuality > GpsQualityPtr;
typedef boost::shared_ptr< ::my_msgs::GpsQuality const> GpsQualityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::GpsQuality_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::GpsQuality_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::GpsQuality_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::GpsQuality_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::GpsQuality_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::GpsQuality_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::GpsQuality_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::GpsQuality_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::GpsQuality_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e07c7995fc75675df578842b77b55ffa";
  }

  static const char* value(const ::my_msgs::GpsQuality_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe07c7995fc75675dULL;
  static const uint64_t static_value2 = 0xf578842b77b55ffaULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::GpsQuality_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/GpsQuality";
  }

  static const char* value(const ::my_msgs::GpsQuality_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::GpsQuality_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 FIX_NO\n\
int32 FIX_2D\n\
int32 FIX_3D\n\
int32 FIX_INVALID\n\
";
  }

  static const char* value(const ::my_msgs::GpsQuality_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::GpsQuality_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FIX_NO);
      stream.next(m.FIX_2D);
      stream.next(m.FIX_3D);
      stream.next(m.FIX_INVALID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsQuality_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::GpsQuality_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::GpsQuality_<ContainerAllocator>& v)
  {
    s << indent << "FIX_NO: ";
    Printer<int32_t>::stream(s, indent + "  ", v.FIX_NO);
    s << indent << "FIX_2D: ";
    Printer<int32_t>::stream(s, indent + "  ", v.FIX_2D);
    s << indent << "FIX_3D: ";
    Printer<int32_t>::stream(s, indent + "  ", v.FIX_3D);
    s << indent << "FIX_INVALID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.FIX_INVALID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_GPSQUALITY_H
