// Generated by gencpp from file my_msgs/InputDebug.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_INPUTDEBUG_H
#define MY_MSGS_MESSAGE_INPUTDEBUG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_msgs/Header.h>
#include <my_msgs/Header.h>
#include <my_msgs/Header.h>

namespace my_msgs
{
template <class ContainerAllocator>
struct InputDebug_
{
  typedef InputDebug_<ContainerAllocator> Type;

  InputDebug_()
    : localization_header()
    , canbus_header()
    , trajectory_header()  {
    }
  InputDebug_(const ContainerAllocator& _alloc)
    : localization_header(_alloc)
    , canbus_header(_alloc)
    , trajectory_header(_alloc)  {
  (void)_alloc;
    }



   typedef  ::my_msgs::Header_<ContainerAllocator>  _localization_header_type;
  _localization_header_type localization_header;

   typedef  ::my_msgs::Header_<ContainerAllocator>  _canbus_header_type;
  _canbus_header_type canbus_header;

   typedef  ::my_msgs::Header_<ContainerAllocator>  _trajectory_header_type;
  _trajectory_header_type trajectory_header;




  typedef boost::shared_ptr< ::my_msgs::InputDebug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::InputDebug_<ContainerAllocator> const> ConstPtr;

}; // struct InputDebug_

typedef ::my_msgs::InputDebug_<std::allocator<void> > InputDebug;

typedef boost::shared_ptr< ::my_msgs::InputDebug > InputDebugPtr;
typedef boost::shared_ptr< ::my_msgs::InputDebug const> InputDebugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::InputDebug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::InputDebug_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::InputDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::InputDebug_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::InputDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::InputDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::InputDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::InputDebug_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::InputDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31af8a71bf5ba4d087d20172a8a5d8cd";
  }

  static const char* value(const ::my_msgs::InputDebug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31af8a71bf5ba4d0ULL;
  static const uint64_t static_value2 = 0x87d20172a8a5d8cdULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::InputDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/InputDebug";
  }

  static const char* value(const ::my_msgs::InputDebug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::InputDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/Header localization_header\n\
my_msgs/Header canbus_header\n\
my_msgs/Header trajectory_header\n\
================================================================================\n\
MSG: my_msgs/Header\n\
float64 timestamp_sec\n\
string module_name\n\
uint32 sequence_num\n\
uint32 lidar_timestamp\n\
uint32 camera_timestamp\n\
uint32 radar_timestamp\n\
uint32 version\n\
my_msgs/Status status\n\
\n\
================================================================================\n\
MSG: my_msgs/Status\n\
int32 error_code\n\
";
  }

  static const char* value(const ::my_msgs::InputDebug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::InputDebug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.localization_header);
      stream.next(m.canbus_header);
      stream.next(m.trajectory_header);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InputDebug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::InputDebug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::InputDebug_<ContainerAllocator>& v)
  {
    s << indent << "localization_header: ";
    s << std::endl;
    Printer< ::my_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.localization_header);
    s << indent << "canbus_header: ";
    s << std::endl;
    Printer< ::my_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.canbus_header);
    s << indent << "trajectory_header: ";
    s << std::endl;
    Printer< ::my_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory_header);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_INPUTDEBUG_H
