// Generated by gencpp from file my_msgs/MainNotReady.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_MAINNOTREADY_H
#define MY_MSGS_MESSAGE_MAINNOTREADY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_msgs
{
template <class ContainerAllocator>
struct MainNotReady_
{
  typedef MainNotReady_<ContainerAllocator> Type;

  MainNotReady_()
    : reason()  {
    }
  MainNotReady_(const ContainerAllocator& _alloc)
    : reason(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _reason_type;
  _reason_type reason;




  typedef boost::shared_ptr< ::my_msgs::MainNotReady_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::MainNotReady_<ContainerAllocator> const> ConstPtr;

}; // struct MainNotReady_

typedef ::my_msgs::MainNotReady_<std::allocator<void> > MainNotReady;

typedef boost::shared_ptr< ::my_msgs::MainNotReady > MainNotReadyPtr;
typedef boost::shared_ptr< ::my_msgs::MainNotReady const> MainNotReadyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::MainNotReady_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::MainNotReady_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::MainNotReady_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::MainNotReady_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::MainNotReady_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::MainNotReady_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::MainNotReady_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::MainNotReady_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::MainNotReady_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a280da32bbce672d6bdb55a7f298c5c0";
  }

  static const char* value(const ::my_msgs::MainNotReady_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa280da32bbce672dULL;
  static const uint64_t static_value2 = 0x6bdb55a7f298c5c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::MainNotReady_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/MainNotReady";
  }

  static const char* value(const ::my_msgs::MainNotReady_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::MainNotReady_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string reason\n\
";
  }

  static const char* value(const ::my_msgs::MainNotReady_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::MainNotReady_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reason);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MainNotReady_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::MainNotReady_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::MainNotReady_<ContainerAllocator>& v)
  {
    s << indent << "reason: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.reason);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_MAINNOTREADY_H
