// Generated by gencpp from file my_msgs/MainDecision.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_MAINDECISION_H
#define MY_MSGS_MESSAGE_MAINDECISION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_msgs/MainMissionComplete.h>
#include <my_msgs/MainNotReady.h>
#include <my_msgs/MainParking.h>

namespace my_msgs
{
template <class ContainerAllocator>
struct MainDecision_
{
  typedef MainDecision_<ContainerAllocator> Type;

  MainDecision_()
    : mission_complete()
    , not_ready()
    , parking()  {
    }
  MainDecision_(const ContainerAllocator& _alloc)
    : mission_complete(_alloc)
    , not_ready(_alloc)
    , parking(_alloc)  {
  (void)_alloc;
    }



   typedef  ::my_msgs::MainMissionComplete_<ContainerAllocator>  _mission_complete_type;
  _mission_complete_type mission_complete;

   typedef  ::my_msgs::MainNotReady_<ContainerAllocator>  _not_ready_type;
  _not_ready_type not_ready;

   typedef  ::my_msgs::MainParking_<ContainerAllocator>  _parking_type;
  _parking_type parking;




  typedef boost::shared_ptr< ::my_msgs::MainDecision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::MainDecision_<ContainerAllocator> const> ConstPtr;

}; // struct MainDecision_

typedef ::my_msgs::MainDecision_<std::allocator<void> > MainDecision;

typedef boost::shared_ptr< ::my_msgs::MainDecision > MainDecisionPtr;
typedef boost::shared_ptr< ::my_msgs::MainDecision const> MainDecisionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::MainDecision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::MainDecision_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::MainDecision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::MainDecision_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::MainDecision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::MainDecision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::MainDecision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::MainDecision_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::MainDecision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf741b549debf7f8e19453190e85c513";
  }

  static const char* value(const ::my_msgs::MainDecision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf741b549debf7f8ULL;
  static const uint64_t static_value2 = 0xe19453190e85c513ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::MainDecision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/MainDecision";
  }

  static const char* value(const ::my_msgs::MainDecision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::MainDecision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/MainMissionComplete mission_complete\n\
my_msgs/MainNotReady not_ready\n\
my_msgs/MainParking parking\n\
================================================================================\n\
MSG: my_msgs/MainMissionComplete\n\
my_msgs/PointENU stop_point32\n\
float64 stop_heading\n\
================================================================================\n\
MSG: my_msgs/PointENU\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: my_msgs/MainNotReady\n\
string reason\n\
================================================================================\n\
MSG: my_msgs/MainParking\n\
";
  }

  static const char* value(const ::my_msgs::MainDecision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::MainDecision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mission_complete);
      stream.next(m.not_ready);
      stream.next(m.parking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MainDecision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::MainDecision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::MainDecision_<ContainerAllocator>& v)
  {
    s << indent << "mission_complete: ";
    s << std::endl;
    Printer< ::my_msgs::MainMissionComplete_<ContainerAllocator> >::stream(s, indent + "  ", v.mission_complete);
    s << indent << "not_ready: ";
    s << std::endl;
    Printer< ::my_msgs::MainNotReady_<ContainerAllocator> >::stream(s, indent + "  ", v.not_ready);
    s << indent << "parking: ";
    s << std::endl;
    Printer< ::my_msgs::MainParking_<ContainerAllocator> >::stream(s, indent + "  ", v.parking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_MAINDECISION_H
