// Generated by gencpp from file my_msgs/ObjectNudge.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_OBJECTNUDGE_H
#define MY_MSGS_MESSAGE_OBJECTNUDGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_msgs/NudgeType.h>

namespace my_msgs
{
template <class ContainerAllocator>
struct ObjectNudge_
{
  typedef ObjectNudge_<ContainerAllocator> Type;

  ObjectNudge_()
    : type()
    , distance_l(0.0)  {
    }
  ObjectNudge_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , distance_l(0.0)  {
  (void)_alloc;
    }



   typedef  ::my_msgs::NudgeType_<ContainerAllocator>  _type_type;
  _type_type type;

   typedef double _distance_l_type;
  _distance_l_type distance_l;




  typedef boost::shared_ptr< ::my_msgs::ObjectNudge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::ObjectNudge_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectNudge_

typedef ::my_msgs::ObjectNudge_<std::allocator<void> > ObjectNudge;

typedef boost::shared_ptr< ::my_msgs::ObjectNudge > ObjectNudgePtr;
typedef boost::shared_ptr< ::my_msgs::ObjectNudge const> ObjectNudgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::ObjectNudge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::ObjectNudge_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::ObjectNudge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::ObjectNudge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::ObjectNudge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::ObjectNudge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::ObjectNudge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::ObjectNudge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::ObjectNudge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fbcff6db9cf4795f957540579f51b888";
  }

  static const char* value(const ::my_msgs::ObjectNudge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfbcff6db9cf4795fULL;
  static const uint64_t static_value2 = 0x957540579f51b888ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::ObjectNudge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/ObjectNudge";
  }

  static const char* value(const ::my_msgs::ObjectNudge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::ObjectNudge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/NudgeType type\n\
float64 distance_l\n\
================================================================================\n\
MSG: my_msgs/NudgeType\n\
int32 LEFT_NUDGE\n\
int32 RIGHT_NUDGE\n\
int32 NO_NUDGE\n\
";
  }

  static const char* value(const ::my_msgs::ObjectNudge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::ObjectNudge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.distance_l);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectNudge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::ObjectNudge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::ObjectNudge_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    s << std::endl;
    Printer< ::my_msgs::NudgeType_<ContainerAllocator> >::stream(s, indent + "  ", v.type);
    s << indent << "distance_l: ";
    Printer<double>::stream(s, indent + "  ", v.distance_l);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_OBJECTNUDGE_H
