// Generated by gencpp from file my_msgs/ObjectDecisionType.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_OBJECTDECISIONTYPE_H
#define MY_MSGS_MESSAGE_OBJECTDECISIONTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_msgs/ObjectIgnore.h>
#include <my_msgs/ObjectStop.h>
#include <my_msgs/ObjectFollow.h>
#include <my_msgs/ObjectYield.h>
#include <my_msgs/ObjectOvertake.h>
#include <my_msgs/ObjectNudge.h>
#include <my_msgs/ObjectSidePass.h>
#include <my_msgs/ObjectAvoid.h>

namespace my_msgs
{
template <class ContainerAllocator>
struct ObjectDecisionType_
{
  typedef ObjectDecisionType_<ContainerAllocator> Type;

  ObjectDecisionType_()
    : ignore()
    , stop()
    , follow()
    , Yield()
    , overtake()
    , nudge()
    , sidepass()
    , avoid()  {
    }
  ObjectDecisionType_(const ContainerAllocator& _alloc)
    : ignore(_alloc)
    , stop(_alloc)
    , follow(_alloc)
    , Yield(_alloc)
    , overtake(_alloc)
    , nudge(_alloc)
    , sidepass(_alloc)
    , avoid(_alloc)  {
  (void)_alloc;
    }



   typedef  ::my_msgs::ObjectIgnore_<ContainerAllocator>  _ignore_type;
  _ignore_type ignore;

   typedef  ::my_msgs::ObjectStop_<ContainerAllocator>  _stop_type;
  _stop_type stop;

   typedef  ::my_msgs::ObjectFollow_<ContainerAllocator>  _follow_type;
  _follow_type follow;

   typedef  ::my_msgs::ObjectYield_<ContainerAllocator>  _Yield_type;
  _Yield_type Yield;

   typedef  ::my_msgs::ObjectOvertake_<ContainerAllocator>  _overtake_type;
  _overtake_type overtake;

   typedef  ::my_msgs::ObjectNudge_<ContainerAllocator>  _nudge_type;
  _nudge_type nudge;

   typedef  ::my_msgs::ObjectSidePass_<ContainerAllocator>  _sidepass_type;
  _sidepass_type sidepass;

   typedef  ::my_msgs::ObjectAvoid_<ContainerAllocator>  _avoid_type;
  _avoid_type avoid;




  typedef boost::shared_ptr< ::my_msgs::ObjectDecisionType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::ObjectDecisionType_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDecisionType_

typedef ::my_msgs::ObjectDecisionType_<std::allocator<void> > ObjectDecisionType;

typedef boost::shared_ptr< ::my_msgs::ObjectDecisionType > ObjectDecisionTypePtr;
typedef boost::shared_ptr< ::my_msgs::ObjectDecisionType const> ObjectDecisionTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::ObjectDecisionType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::ObjectDecisionType_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::ObjectDecisionType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::ObjectDecisionType_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::ObjectDecisionType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::ObjectDecisionType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::ObjectDecisionType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::ObjectDecisionType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::ObjectDecisionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "202ac4dd0b2cf11858322ce292b42e36";
  }

  static const char* value(const ::my_msgs::ObjectDecisionType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x202ac4dd0b2cf118ULL;
  static const uint64_t static_value2 = 0x58322ce292b42e36ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::ObjectDecisionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/ObjectDecisionType";
  }

  static const char* value(const ::my_msgs::ObjectDecisionType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::ObjectDecisionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/ObjectIgnore ignore\n\
my_msgs/ObjectStop stop\n\
my_msgs/ObjectFollow follow\n\
my_msgs/ObjectYield Yield\n\
my_msgs/ObjectOvertake overtake\n\
my_msgs/ObjectNudge nudge\n\
my_msgs/ObjectSidePass sidepass\n\
my_msgs/ObjectAvoid avoid\n\
================================================================================\n\
MSG: my_msgs/ObjectIgnore\n\
\n\
================================================================================\n\
MSG: my_msgs/ObjectStop\n\
my_msgs/StopReasonCode reason_code\n\
float64 distance_s\n\
my_msgs/PointENU stop_point32\n\
float64 stop_heading\n\
byte[] wait_for_obstacle\n\
================================================================================\n\
MSG: my_msgs/StopReasonCode\n\
int32 STOP_REASON_HEAD_VEHICLE\n\
int32 STOP_REASON_DESTINATION\n\
int32 STOP_REASON_PEDESTRIAN\n\
int32 STOP_REASON_OBSTACLE\n\
int32 STOP_REASON_PREPARKING\n\
int32 STOP_REASON_SIGNAL\n\
int32 STOP_REASON_STOP_SIGN\n\
int32 STOP_REASON_YIELD_SIGN\n\
int32 STOP_REASON_CLEAR_ZONE\n\
int32 STOP_REASON_CROSSWALK\n\
int32 STOP_REASON_CREEPER\n\
int32 STOP_REASON_REFERENCE_END\n\
int32 STOP_REASON_YELLOW_SIGNAL\n\
int32 STOP_REASON_PULL_OVER\n\
================================================================================\n\
MSG: my_msgs/PointENU\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: my_msgs/ObjectFollow\n\
float64 distance_s\n\
my_msgs/PointENU fence_point32\n\
float64 fence_heading\n\
================================================================================\n\
MSG: my_msgs/ObjectYield\n\
float64 distance_s\n\
my_msgs/PointENU fence_point32\n\
float64 fence_heading\n\
float64 time_buffer\n\
================================================================================\n\
MSG: my_msgs/ObjectOvertake\n\
float64 distance_s\n\
my_msgs/PointENU fence_point32\n\
float64 fence_heading\n\
float64 time_buffer\n\
================================================================================\n\
MSG: my_msgs/ObjectNudge\n\
my_msgs/NudgeType type\n\
float64 distance_l\n\
================================================================================\n\
MSG: my_msgs/NudgeType\n\
int32 LEFT_NUDGE\n\
int32 RIGHT_NUDGE\n\
int32 NO_NUDGE\n\
================================================================================\n\
MSG: my_msgs/ObjectSidePass\n\
my_msgs/SidePassType type\n\
================================================================================\n\
MSG: my_msgs/SidePassType\n\
int32 LEFT\n\
int32 RIGHT\n\
================================================================================\n\
MSG: my_msgs/ObjectAvoid\n\
";
  }

  static const char* value(const ::my_msgs::ObjectDecisionType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::ObjectDecisionType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ignore);
      stream.next(m.stop);
      stream.next(m.follow);
      stream.next(m.Yield);
      stream.next(m.overtake);
      stream.next(m.nudge);
      stream.next(m.sidepass);
      stream.next(m.avoid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDecisionType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::ObjectDecisionType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::ObjectDecisionType_<ContainerAllocator>& v)
  {
    s << indent << "ignore: ";
    s << std::endl;
    Printer< ::my_msgs::ObjectIgnore_<ContainerAllocator> >::stream(s, indent + "  ", v.ignore);
    s << indent << "stop: ";
    s << std::endl;
    Printer< ::my_msgs::ObjectStop_<ContainerAllocator> >::stream(s, indent + "  ", v.stop);
    s << indent << "follow: ";
    s << std::endl;
    Printer< ::my_msgs::ObjectFollow_<ContainerAllocator> >::stream(s, indent + "  ", v.follow);
    s << indent << "Yield: ";
    s << std::endl;
    Printer< ::my_msgs::ObjectYield_<ContainerAllocator> >::stream(s, indent + "  ", v.Yield);
    s << indent << "overtake: ";
    s << std::endl;
    Printer< ::my_msgs::ObjectOvertake_<ContainerAllocator> >::stream(s, indent + "  ", v.overtake);
    s << indent << "nudge: ";
    s << std::endl;
    Printer< ::my_msgs::ObjectNudge_<ContainerAllocator> >::stream(s, indent + "  ", v.nudge);
    s << indent << "sidepass: ";
    s << std::endl;
    Printer< ::my_msgs::ObjectSidePass_<ContainerAllocator> >::stream(s, indent + "  ", v.sidepass);
    s << indent << "avoid: ";
    s << std::endl;
    Printer< ::my_msgs::ObjectAvoid_<ContainerAllocator> >::stream(s, indent + "  ", v.avoid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_OBJECTDECISIONTYPE_H
