// Generated by gencpp from file my_msgs/PerceptionObstacle.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_PERCEPTIONOBSTACLE_H
#define MY_MSGS_MESSAGE_PERCEPTIONOBSTACLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_msgs/Point3D.h>
#include <my_msgs/Point3D.h>
#include <my_msgs/Point3D.h>

namespace my_msgs
{
template <class ContainerAllocator>
struct PerceptionObstacle_
{
  typedef PerceptionObstacle_<ContainerAllocator> Type;

  PerceptionObstacle_()
    : id(0)
    , position()
    , theta(0.0)
    , velocity()
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , polygon_point()
    , tracking_time(0.0)
    , type(0)
    , timestamp(0.0)
    , confidence(0.0)
    , confidence_type(0)  {
    }
  PerceptionObstacle_(const ContainerAllocator& _alloc)
    : id(0)
    , position(_alloc)
    , theta(0.0)
    , velocity(_alloc)
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , polygon_point(_alloc)
    , tracking_time(0.0)
    , type(0)
    , timestamp(0.0)
    , confidence(0.0)
    , confidence_type(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::my_msgs::Point3D_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _theta_type;
  _theta_type theta;

   typedef  ::my_msgs::Point3D_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef double _length_type;
  _length_type length;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;

   typedef std::vector< ::my_msgs::Point3D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::my_msgs::Point3D_<ContainerAllocator> >::other >  _polygon_point_type;
  _polygon_point_type polygon_point;

   typedef double _tracking_time_type;
  _tracking_time_type tracking_time;

   typedef int32_t _type_type;
  _type_type type;

   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef double _confidence_type;
  _confidence_type confidence;

   typedef int32_t _confidence_type_type;
  _confidence_type_type confidence_type;




  typedef boost::shared_ptr< ::my_msgs::PerceptionObstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::PerceptionObstacle_<ContainerAllocator> const> ConstPtr;

}; // struct PerceptionObstacle_

typedef ::my_msgs::PerceptionObstacle_<std::allocator<void> > PerceptionObstacle;

typedef boost::shared_ptr< ::my_msgs::PerceptionObstacle > PerceptionObstaclePtr;
typedef boost::shared_ptr< ::my_msgs::PerceptionObstacle const> PerceptionObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::PerceptionObstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::PerceptionObstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::PerceptionObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::PerceptionObstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::PerceptionObstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::PerceptionObstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::PerceptionObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::PerceptionObstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::PerceptionObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ea6091f7116eabfdb52a23e9b251032";
  }

  static const char* value(const ::my_msgs::PerceptionObstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ea6091f7116eabfULL;
  static const uint64_t static_value2 = 0xdb52a23e9b251032ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::PerceptionObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/PerceptionObstacle";
  }

  static const char* value(const ::my_msgs::PerceptionObstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::PerceptionObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
my_msgs/Point3D position\n\
float64 theta \n\
my_msgs/Point3D velocity\n\
float64 length\n\
float64 width\n\
float64 height\n\
my_msgs/Point3D[] polygon_point\n\
float64 tracking_time\n\
int32 type\n\
float64 timestamp\n\
float64 confidence\n\
int32 confidence_type\n\
================================================================================\n\
MSG: my_msgs/Point3D\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::my_msgs::PerceptionObstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::PerceptionObstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.theta);
      stream.next(m.velocity);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.polygon_point);
      stream.next(m.tracking_time);
      stream.next(m.type);
      stream.next(m.timestamp);
      stream.next(m.confidence);
      stream.next(m.confidence_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PerceptionObstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::PerceptionObstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::PerceptionObstacle_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::my_msgs::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::my_msgs::Point3D_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "length: ";
    Printer<double>::stream(s, indent + "  ", v.length);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "polygon_point[]" << std::endl;
    for (size_t i = 0; i < v.polygon_point.size(); ++i)
    {
      s << indent << "  polygon_point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::my_msgs::Point3D_<ContainerAllocator> >::stream(s, indent + "    ", v.polygon_point[i]);
    }
    s << indent << "tracking_time: ";
    Printer<double>::stream(s, indent + "  ", v.tracking_time);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "confidence_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.confidence_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_PERCEPTIONOBSTACLE_H
