// Generated by gencpp from file my_msgs/RoutingRequest.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_ROUTINGREQUEST_H
#define MY_MSGS_MESSAGE_ROUTINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_msgs/Header.h>
#include <my_msgs/LaneWayPoint.h>
#include <my_msgs/LaneSegment.h>

namespace my_msgs
{
template <class ContainerAllocator>
struct RoutingRequest_
{
  typedef RoutingRequest_<ContainerAllocator> Type;

  RoutingRequest_()
    : header()
    , waypoint()
    , blacklisted_lane()
    , blacklisted_road()
    , broadcast(false)  {
    }
  RoutingRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , waypoint(_alloc)
    , blacklisted_lane(_alloc)
    , blacklisted_road(_alloc)
    , broadcast(false)  {
  (void)_alloc;
    }



   typedef  ::my_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::my_msgs::LaneWayPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::my_msgs::LaneWayPoint_<ContainerAllocator> >::other >  _waypoint_type;
  _waypoint_type waypoint;

   typedef  ::my_msgs::LaneSegment_<ContainerAllocator>  _blacklisted_lane_type;
  _blacklisted_lane_type blacklisted_lane;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _blacklisted_road_type;
  _blacklisted_road_type blacklisted_road;

   typedef uint8_t _broadcast_type;
  _broadcast_type broadcast;




  typedef boost::shared_ptr< ::my_msgs::RoutingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::RoutingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RoutingRequest_

typedef ::my_msgs::RoutingRequest_<std::allocator<void> > RoutingRequest;

typedef boost::shared_ptr< ::my_msgs::RoutingRequest > RoutingRequestPtr;
typedef boost::shared_ptr< ::my_msgs::RoutingRequest const> RoutingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::RoutingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::RoutingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::RoutingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::RoutingRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::RoutingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::RoutingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::RoutingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::RoutingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::RoutingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73e1fdee89d3972dbf924d2c247c7b57";
  }

  static const char* value(const ::my_msgs::RoutingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73e1fdee89d3972dULL;
  static const uint64_t static_value2 = 0xbf924d2c247c7b57ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::RoutingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/RoutingRequest";
  }

  static const char* value(const ::my_msgs::RoutingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::RoutingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/Header header\n\
my_msgs/LaneWayPoint[] waypoint\n\
my_msgs/LaneSegment blacklisted_lane \n\
string[] blacklisted_road \n\
bool broadcast\n\
================================================================================\n\
MSG: my_msgs/Header\n\
float64 timestamp_sec\n\
string module_name\n\
uint32 sequence_num\n\
uint32 lidar_timestamp\n\
uint32 camera_timestamp\n\
uint32 radar_timestamp\n\
uint32 version\n\
my_msgs/Status status\n\
\n\
================================================================================\n\
MSG: my_msgs/Status\n\
int32 error_code\n\
\n\
================================================================================\n\
MSG: my_msgs/LaneWayPoint\n\
string id\n\
float64 s\n\
my_msgs/PointENU pose\n\
================================================================================\n\
MSG: my_msgs/PointENU\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: my_msgs/LaneSegment\n\
string id\n\
float64 start_s\n\
float64 end_s\n\
";
  }

  static const char* value(const ::my_msgs::RoutingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::RoutingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.waypoint);
      stream.next(m.blacklisted_lane);
      stream.next(m.blacklisted_road);
      stream.next(m.broadcast);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoutingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::RoutingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::RoutingRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::my_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "waypoint[]" << std::endl;
    for (size_t i = 0; i < v.waypoint.size(); ++i)
    {
      s << indent << "  waypoint[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::my_msgs::LaneWayPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoint[i]);
    }
    s << indent << "blacklisted_lane: ";
    s << std::endl;
    Printer< ::my_msgs::LaneSegment_<ContainerAllocator> >::stream(s, indent + "  ", v.blacklisted_lane);
    s << indent << "blacklisted_road[]" << std::endl;
    for (size_t i = 0; i < v.blacklisted_road.size(); ++i)
    {
      s << indent << "  blacklisted_road[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.blacklisted_road[i]);
    }
    s << indent << "broadcast: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.broadcast);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_ROUTINGREQUEST_H
