// Generated by gencpp from file my_msgs/Test.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_TEST_H
#define MY_MSGS_MESSAGE_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_msgs
{
template <class ContainerAllocator>
struct Test_
{
  typedef Test_<ContainerAllocator> Type;

  Test_()
    : String_test()  {
    }
  Test_(const ContainerAllocator& _alloc)
    : String_test(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _String_test_type;
  _String_test_type String_test;




  typedef boost::shared_ptr< ::my_msgs::Test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::Test_<ContainerAllocator> const> ConstPtr;

}; // struct Test_

typedef ::my_msgs::Test_<std::allocator<void> > Test;

typedef boost::shared_ptr< ::my_msgs::Test > TestPtr;
typedef boost::shared_ptr< ::my_msgs::Test const> TestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::Test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::Test_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::Test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::Test_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::Test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::Test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::Test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::Test_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937187df5e2181f20cc662012ff61629";
  }

  static const char* value(const ::my_msgs::Test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937187df5e2181f2ULL;
  static const uint64_t static_value2 = 0x0cc662012ff61629ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/Test";
  }

  static const char* value(const ::my_msgs::Test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::Test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] String_test\n\
";
  }

  static const char* value(const ::my_msgs::Test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::Test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.String_test);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::Test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::Test_<ContainerAllocator>& v)
  {
    s << indent << "String_test[]" << std::endl;
    for (size_t i = 0; i < v.String_test.size(); ++i)
    {
      s << indent << "  String_test[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.String_test[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_TEST_H
