// Generated by gencpp from file my_msgs/TurnSignal.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_TURNSIGNAL_H
#define MY_MSGS_MESSAGE_TURNSIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_msgs
{
template <class ContainerAllocator>
struct TurnSignal_
{
  typedef TurnSignal_<ContainerAllocator> Type;

  TurnSignal_()
    : TURN_NONE(0)
    , TURN_LEFT(0)
    , TURN_RIGHT(0)  {
    }
  TurnSignal_(const ContainerAllocator& _alloc)
    : TURN_NONE(0)
    , TURN_LEFT(0)
    , TURN_RIGHT(0)  {
  (void)_alloc;
    }



   typedef int32_t _TURN_NONE_type;
  _TURN_NONE_type TURN_NONE;

   typedef int32_t _TURN_LEFT_type;
  _TURN_LEFT_type TURN_LEFT;

   typedef int32_t _TURN_RIGHT_type;
  _TURN_RIGHT_type TURN_RIGHT;




  typedef boost::shared_ptr< ::my_msgs::TurnSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::TurnSignal_<ContainerAllocator> const> ConstPtr;

}; // struct TurnSignal_

typedef ::my_msgs::TurnSignal_<std::allocator<void> > TurnSignal;

typedef boost::shared_ptr< ::my_msgs::TurnSignal > TurnSignalPtr;
typedef boost::shared_ptr< ::my_msgs::TurnSignal const> TurnSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::TurnSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::TurnSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/home/tmp/ros/share/std_msgs/cmake/../msg'], 'my_msgs': ['/apollo/ros_pkgs/src/my_msgs/msg', '/apollo/ros_pkgs/src/my_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::TurnSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::TurnSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::TurnSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::TurnSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::TurnSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::TurnSignal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::TurnSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48d2bdbb0effc29401668258d61f54d4";
  }

  static const char* value(const ::my_msgs::TurnSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48d2bdbb0effc294ULL;
  static const uint64_t static_value2 = 0x01668258d61f54d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::TurnSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/TurnSignal";
  }

  static const char* value(const ::my_msgs::TurnSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::TurnSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 TURN_NONE\n\
int32 TURN_LEFT\n\
int32 TURN_RIGHT\n\
";
  }

  static const char* value(const ::my_msgs::TurnSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::TurnSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TURN_NONE);
      stream.next(m.TURN_LEFT);
      stream.next(m.TURN_RIGHT);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::TurnSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::TurnSignal_<ContainerAllocator>& v)
  {
    s << indent << "TURN_NONE: ";
    Printer<int32_t>::stream(s, indent + "  ", v.TURN_NONE);
    s << indent << "TURN_LEFT: ";
    Printer<int32_t>::stream(s, indent + "  ", v.TURN_LEFT);
    s << indent << "TURN_RIGHT: ";
    Printer<int32_t>::stream(s, indent + "  ", v.TURN_RIGHT);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_TURNSIGNAL_H
