# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_msgs/LatencyStats.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LatencyStats(genpy.Message):
  _md5sum = "ba8956e611867e226f8110461f01e090"
  _type = "my_msgs/LatencyStats"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 total_time_ms
float64[] controller_time_ms
bool total_time_exceeded
"""
  __slots__ = ['total_time_ms','controller_time_ms','total_time_exceeded']
  _slot_types = ['float64','float64[]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       total_time_ms,controller_time_ms,total_time_exceeded

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LatencyStats, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.total_time_ms is None:
        self.total_time_ms = 0.
      if self.controller_time_ms is None:
        self.controller_time_ms = []
      if self.total_time_exceeded is None:
        self.total_time_exceeded = False
    else:
      self.total_time_ms = 0.
      self.controller_time_ms = []
      self.total_time_exceeded = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_d.pack(self.total_time_ms))
      length = len(self.controller_time_ms)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.controller_time_ms))
      buff.write(_struct_B.pack(self.total_time_exceeded))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 8
      (self.total_time_ms,) = _struct_d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.controller_time_ms = struct.unpack(pattern, str[start:end])
      start = end
      end += 1
      (self.total_time_exceeded,) = _struct_B.unpack(str[start:end])
      self.total_time_exceeded = bool(self.total_time_exceeded)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_d.pack(self.total_time_ms))
      length = len(self.controller_time_ms)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.controller_time_ms.tostring())
      buff.write(_struct_B.pack(self.total_time_exceeded))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 8
      (self.total_time_ms,) = _struct_d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.controller_time_ms = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 1
      (self.total_time_exceeded,) = _struct_B.unpack(str[start:end])
      self.total_time_exceeded = bool(self.total_time_exceeded)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
_struct_d = struct.Struct("<d")
