# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_msgs/TurnSignal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TurnSignal(genpy.Message):
  _md5sum = "48d2bdbb0effc29401668258d61f54d4"
  _type = "my_msgs/TurnSignal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 TURN_NONE
int32 TURN_LEFT
int32 TURN_RIGHT"""
  __slots__ = ['TURN_NONE','TURN_LEFT','TURN_RIGHT']
  _slot_types = ['int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       TURN_NONE,TURN_LEFT,TURN_RIGHT

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TurnSignal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.TURN_NONE is None:
        self.TURN_NONE = 0
      if self.TURN_LEFT is None:
        self.TURN_LEFT = 0
      if self.TURN_RIGHT is None:
        self.TURN_RIGHT = 0
    else:
      self.TURN_NONE = 0
      self.TURN_LEFT = 0
      self.TURN_RIGHT = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3i.pack(_x.TURN_NONE, _x.TURN_LEFT, _x.TURN_RIGHT))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.TURN_NONE, _x.TURN_LEFT, _x.TURN_RIGHT,) = _struct_3i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3i.pack(_x.TURN_NONE, _x.TURN_LEFT, _x.TURN_RIGHT))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.TURN_NONE, _x.TURN_LEFT, _x.TURN_RIGHT,) = _struct_3i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3i = struct.Struct("<3i")
