(cl:in-package my_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          THROTTLE-VAL
          THROTTLE
          BRAKE-VAL
          BRAKE
          STEERING_RATE-VAL
          STEERING_RATE
          STEERING_TARGET-VAL
          STEERING_TARGET
          PARKING_BRAKE-VAL
          PARKING_BRAKE
          SPEED-VAL
          SPEED
          ACCELERATION-VAL
          ACCELERATION
          RESET_MODEL-VAL
          RESET_MODEL
          ENGINE_ON_OFF-VAL
          ENGINE_ON_OFF
          GEAR_LOCATION-VAL
          GEAR_LOCATION
          TRAJECTORY_FRACTION-VAL
          TRAJECTORY_FRACTION
          DRIVING_MODE-VAL
          DRIVING_MODE
          GEAR_POSITION-VAL
          GEAR_POSITION
          SIGNAL-VAL
          SIGNAL
          LATENCY_STATS-VAL
          LATENCY_STATS
          PAD_MSG-VAL
          PAD_MSG
          ENGAGE_ADVICE-VAL
          ENGAGE_ADVICE
          IS_IN_SAFE_MODE-VAL
          IS_IN_SAFE_MODE
          LEFT_TURN-VAL
          LEFT_TURN
          RIGHT_TURN-VAL
          RIGHT_TURN
          HIGH_BEAM-VAL
          HIGH_BEAM
          LOW_BEAM-VAL
          LOW_BEAM
          HORN-VAL
          HORN
          TURN_SIGNAL-VAL
          TURN_SIGNAL
          LATENCYSTATUS-VAL
          LATENCYSTATUS
          DEBUG-VAL
          DEBUG
))