(cl:in-package my_msgs-msg)
(cl:export '(RCS_THRESHOLD_STANDARD-VAL
          RCS_THRESHOLD_STANDARD
          RCS_THRESHOLD_HIGH_SENSITIVITY-VAL
          RCS_THRESHOLD_HIGH_SENSITIVITY
          RCS_THRESHOLD_ERROR-VAL
          RCS_THRESHOLD_ERROR
))