(cl:in-package my_msgs-msg)
(cl:export '(LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          GPS_VALID-VAL
          GPS_VALID
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOURS-VAL
          HOURS
          MINUTES-VAL
          MINUTES
          SECONDS-VAL
          SECONDS
          COMPASS_DIRECTION-VAL
          COMPASS_DIRECTION
          PDOP-VAL
          PDOP
          IS_GPS_FAULT-VAL
          IS_GPS_FAULT
          IS_INFERRED-VAL
          IS_INFERRED
          ALTITUDE-VAL
          ALTITUDE
          HEADING-VAL
          HEADING
          HDOP-VAL
          HDOP
          VDOP-VAL
          VDOP
          QUALITY-VAL
          QUALITY
          NUM_SATELLITES-VAL
          NUM_SATELLITES
          GPS_SPEED-VAL
          GPS_SPEED
))