(cl:in-package my_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CLUSTERORTRACK-VAL
          CLUSTERORTRACK
          OBSTACLE_ID-VAL
          OBSTACLE_ID
          LONGITUDE_DIST-VAL
          LONGITUDE_DIST
          LATERAL_DIST-VAL
          LATERAL_DIST
          LONGITUDE_VEL-VAL
          LONGITUDE_VEL
          LATERAL_VEL-VAL
          LATERAL_VEL
          RCS-VAL
          RCS
          DYNPROP-VAL
          DYNPROP
          LONGITUDE_DIST_RMS-VAL
          LONGITUDE_DIST_RMS
          LATERAL_DIST_RMS-VAL
          LATERAL_DIST_RMS
          LONGITUDE_VEL_RMS-VAL
          LONGITUDE_VEL_RMS
          LATERAL_VEL_RMS-VAL
          LATERAL_VEL_RMS
          PROBEXIST-VAL
          PROBEXIST
          MEAS_STATE-VAL
          MEAS_STATE
          LONGITUDE_ACCEL-VAL
          LONGITUDE_ACCEL
          LATERAL_ACCEL-VAL
          LATERAL_ACCEL
          ORITATION_ANGLE-VAL
          ORITATION_ANGLE
          LONGITUDE_ACCEL_RMS-VAL
          LONGITUDE_ACCEL_RMS
          LATERAL_ACCEL_RMS-VAL
          LATERAL_ACCEL_RMS
          ORITATION_ANGLE_RMS-VAL
          ORITATION_ANGLE_RMS
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          OBSTACLE_CLASS-VAL
          OBSTACLE_CLASS
))